fn_args_density = "Compressed"
indent_style = "Visual"
brace_style = "SameLineWhere"
empty_item_single_line = false
format_strings = true
match_block_trailing_comma = true
reorder_imports = true
spaces_around_ranges = true
use_try_shorthand = true
match_arm_blocks = false
