[files]
extend-exclude = [
    ".git/",
    "autogen/spirv.core.grammar.json",
    "autogen/vk.xml",
    "vulkano/autogen-out/*",
    "CHANGELOG.md",
]
ignore-hidden = false

[default.extend-words]
lod = "lod"
uscaled = "uscaled"

# glslc shader stage names
"vert" = "vert"
"tesc" = "tesc"
"tese" = "tese"
"geom" = "geom"
"task" = "task"
"mesh" = "mesh"
"frag" = "frag"
"comp" = "comp"
"rgen" = "rgen"
"rahit" = "rahit"
"rchit" = "rchit"
"rmiss" = "rmiss"
"rint" = "rint"
"rcall" = "rcall"

[default.extend-identifiers]
ANDed = "ANDed"
