[files]
extend-exclude = [
    ".git/",
    "autogen/spirv.core.grammar.json",
    "autogen/vk.xml",
    "vulkano/autogen-out/*",
    "CHANGELOG.md",
]
ignore-hidden = false

[default.extend-words]
lod = "lod"
uscaled = "uscaled"

[default.extend-identifiers]
ANDed = "ANDed"
