// This file is auto-generated by vulkano autogen from vk.xml header version 1.3.281.
// It should not be edited manually. Changes should be made by editing autogen.


impl Version {
    /// The highest Vulkan API version currently supported by Vulkano.
    ///
    /// It is allowed for applications that use Vulkano to make use of features from higher
    /// versions than this. However, Vulkano itself will not make use of those features and
    /// will not expose their APIs, so they must be accessed by other means.
    ///
    /// The `max_api_version` of an [`Instance`](crate::instance::Instance) equals
    /// `HEADER_VERSION` by default, which locks out features from newer versions. In order
    /// to enable the use of higher versions, the `max_api_version` must be overridden when
    /// creating an instance.
    pub const HEADER_VERSION: Version = Version {
        major: 1,
        minor: 3,
        patch: 281,
    };
}
