[package]
name = "runtime-shader"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "runtime-shader"
path = "main.rs"

[dependencies]
vulkano = { workspace = true }
winit = { workspace = true }
