[package]
name = "shader-include"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "shader-include"
path = "main.rs"

[dependencies]
vulkano = { workspace = true }
vulkano-shaders = { workspace = true }
