[package]
name = "occlusion-query"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "occlusion-query"
path = "main.rs"

[dependencies]
vulkano = { path = "../../vulkano" }
vulkano-shaders = { path = "../../vulkano-shaders" }
winit = "0.28"
