name: Question
description: 'Ask a question. Our #support Discord channel is preferred for questions.'
type: Question
body:
  - type: markdown
    attributes:
      value: >
        Our #support Discord channel is preferred for questions, but if you don't have Discord,
        feel free to ask here. Please don't create an issue to ask if feature X is supported. We
        have a [COVERAGE.md](https://github.com/vulkano-rs/vulkano/blob/master/COVERAGE.md) file.
  - type: textarea
    id: description
    attributes:
      label: Question description
    validations:
      required: true
