[package]
name = "basic-compute-shader"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "basic-compute-shader"
path = "main.rs"

[dependencies]
vulkano = { workspace = true }
vulkano-shaders = { workspace = true }
