[package]
name = "pipeline-caching"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "pipeline-caching"
path = "main.rs"

[dependencies]
vulkano = { path = "../../vulkano" }
vulkano-shaders = { path = "../../vulkano-shaders" }
