[package]
name = "multiview"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "multiview"
path = "main.rs"

[dependencies]
png = { workspace = true }
vulkano = { workspace = true }
vulkano-shaders = { workspace = true }
