[package]
name = "self-copy-buffer"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "self-copy-buffer"
path = "main.rs"

[dependencies]
vulkano = { path = "../../vulkano" }
vulkano-shaders = { path = "../../vulkano-shaders" }
